server:
  port: 8090
  address: 127.0.0.1

logging:
  level: DEBUG

spring:
  #datasource
  datasource:
#    url: jdbc:mysql://192.168.40.219:3306/mc?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://localhost:3306/mc?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
#    username: root
    password: root
#    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #druid
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    maxIdle: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#spring:

mybatis:
  type-aliases-package: com.hunsy.metadata.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.hunsy.metadata.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
